#!/bin/bash
# author kmanna
# date 03.06.2014
# Start multiple parallel throughput-Tests to other VMs
# Assumes iperf servers have been started, e.g.
# iperf -s -p PORT

export vmstart=$1
export vmend=$2
export self=$3
export send_count=$4
export bw=$5

if [[ -z "$vmstart" ]] || [[ -z "$vmend" ]] || [[ -z "$self" ]] || [[ -z "$send_count" ]] || [[ -z "$bw" ]]
then
        echo "Error: usage: $0 <vmstartnr> <vmendnr> <id-of-own-vm> <send_count(t)> <sending bw in Mbit>" >&2
        exit 1
fi

for i in $(seq $vmstart $vmend)
do
        [[ $i -eq $self ]] && continue
	server_port=$((5000+$self));
	report_file="query/testdata/iperf-clientlog_172.16.40.2${i}"
	iperf -u -c "172.16.40.2${i}" -p "$server_port" -t "$send_count" -i 1 -b "${bw}M" &> $report_file &
done
