#!/bin/bash
# Finds duplicate adjacent words

if ! [ "$1" ]
then
	echo "Usage: ${0##*/} <file> ..." >&2
	exit 1
fi

let dup_counter=0
for file in "$@"
do
	let linecount=0
	while read line
	do
		for word in $line
		do
			word="${word,,}"
			if [ "$word" = "$last" ]
			then
				echo "${file}:${linecount}:${word}" >&2
				let "dup_counter++"
			fi
			last="$word"
		done
		let "linecount++"
	done < "$file"
done

echo "Duplicates found: $dup_counter"