#!/bin/bash
# Checks if certain words occur in the specified files

unset wordfile

# Default weasel words
weasels="many|various|very|fairly|several|extremely\
|exceedingly|quite|remarkably|few|surprisingly\
|mostly|largely|huge|tiny|((are|is) a number)\
|excellent|interestingly|significantly\
|substantially|clearly|vast|relatively|completely"

# Check for an alternate weasel file
[ -f "${HOME}/etc/words/weasels" ] && wordfile="${HOME}/etc/words/weasels"
[ -f "${WORDSDIR}/weasels" ] && wordfile="${WORDSDIR}/weasels"
[ -f "words/weasels" ] && wordfile="words/weasels"

if [ "$wordfile" ]
then
	weasels="xyzabc123"
	for w in $(cat "$wordfile")
	do
		weasels="$weasels|$w"
	done
fi

if [ "$1" = "" ]
then
	echo "Usage: ${0##*/} <file> ..." >&2
	exit 1
fi

egrep -H -i -n --color "\\b($weasels)\\b" "$@"

last="$?"

[ "$last" = "1" ] && echo "None found" >&2

exit "$last"
